language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t emilfeldman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emilfeldman/docker-react npm run test

